spring:
  application:
    name: springboot-with-redis
  data:
    redis:
      cluster:
        nodes: redis-redis-cluster:6379
      host: redis-redis-cluster
      port: 6379
      password: tfp4zj9yO1
      username: default
server:
  port: 8080
