spring:
  application:
    name: springboot-with-redis
  data:
    redis:
      sentinel:
        master: mymaster
        nodes: sentinel-redis.default.svc.cluster.local:26379
        username: default
        password: GGt77ukRTU
      host: sentinel-redis.default.svc.cluster.local
      port: 26379
      username: default
      password: GGt77ukRTU
server:
  port: 8080
